// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_behaviac_EBTStatus : ICompareValue<behaviac.EBTStatus>
	{
		public override bool Equal(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_eGameForce : ICompareValue<eGameForce>
	{
		public override bool Equal(eGameForce lhs, eGameForce rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(eGameForce lhs, eGameForce rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(eGameForce lhs, eGameForce rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(eGameForce lhs, eGameForce rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(eGameForce lhs, eGameForce rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(eGameForce lhs, eGameForce rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_eMapDirection : ICompareValue<eMapDirection>
	{
		public override bool Equal(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(eMapDirection lhs, eMapDirection rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_eBrickType : ICompareValue<eBrickType>
	{
		public override bool Equal(eBrickType lhs, eBrickType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(eBrickType lhs, eBrickType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(eBrickType lhs, eBrickType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(eBrickType lhs, eBrickType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(eBrickType lhs, eBrickType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(eBrickType lhs, eBrickType rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_UnityEngine_Vector3 : ICompareValue<UnityEngine.Vector3>
	{
		public override bool Equal(UnityEngine.Vector3 lhs, UnityEngine.Vector3 rhs)
		{
			return (lhs.x == rhs.x) && (lhs.y == rhs.y) && (lhs.z == rhs.z);
		}
		public override bool NotEqual(UnityEngine.Vector3 lhs, UnityEngine.Vector3 rhs)
		{
			return !Equal(lhs, rhs);
		}
	}

	public class CompareValue_UnityEngine_Color : ICompareValue<UnityEngine.Color>
	{
		public override bool Equal(UnityEngine.Color lhs, UnityEngine.Color rhs)
		{
			return (lhs.r == rhs.r) && (lhs.g == rhs.g) && (lhs.b == rhs.b) && (lhs.a == rhs.a);
		}
		public override bool NotEqual(UnityEngine.Color lhs, UnityEngine.Color rhs)
		{
			return !Equal(lhs, rhs);
		}
	}

	public class CompareValue_UnityEngine_Transform : ICompareValue<UnityEngine.Transform>
	{
		public override bool Equal(UnityEngine.Transform lhs, UnityEngine.Transform rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(UnityEngine.Transform lhs, UnityEngine.Transform rhs)
		{
			return !Equal(lhs, rhs);
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		class CInstanceConst_UnityEngine_Vector3 : CInstanceConst<UnityEngine.Vector3>
		{
			IInstanceMember _x;
			IInstanceMember _y;
			IInstanceMember _z;

			public CInstanceConst_UnityEngine_Vector3(string typeName, string valueStr) : base(typeName, valueStr)
			{
				List<string> paramStrs = behaviac.StringUtils.SplitTokensForStruct(valueStr);
				Debug.Check(paramStrs != null && paramStrs.Count == 3);

				_x = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[0]);
				_y = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[1]);
				_z = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[2]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_x != null);
				Debug.Check(_y != null);
				Debug.Check(_z != null);

				_value.x = ((CInstanceMember<float>)_x).GetValue(self);
				_value.y = ((CInstanceMember<float>)_y).GetValue(self);
				_value.z = ((CInstanceMember<float>)_z).GetValue(self);
			}
		};

		class CInstanceConst_UnityEngine_Color : CInstanceConst<UnityEngine.Color>
		{
			IInstanceMember _r;
			IInstanceMember _g;
			IInstanceMember _b;
			IInstanceMember _a;

			public CInstanceConst_UnityEngine_Color(string typeName, string valueStr) : base(typeName, valueStr)
			{
				List<string> paramStrs = behaviac.StringUtils.SplitTokensForStruct(valueStr);
				Debug.Check(paramStrs != null && paramStrs.Count == 4);

				_r = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[0]);
				_g = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[1]);
				_b = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[2]);
				_a = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[3]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_r != null);
				Debug.Check(_g != null);
				Debug.Check(_b != null);
				Debug.Check(_a != null);

				_value.r = ((CInstanceMember<float>)_r).GetValue(self);
				_value.g = ((CInstanceMember<float>)_g).GetValue(self);
				_value.b = ((CInstanceMember<float>)_b).GetValue(self);
				_value.a = ((CInstanceMember<float>)_a).GetValue(self);
			}
		};

		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_GameActor_findPath : CAgentMethodBase<behaviac.EBTStatus>
		{
			CInstanceMember<UnityEngine.Vector3> _param0;
			CInstanceMember<int> _param1;

			public CMethod_GameActor_findPath()
			{
			}

			public CMethod_GameActor_findPath(CMethod_GameActor_findPath rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameActor_findPath(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				if (paramStrs[0].StartsWith("{"))
				{
					_param0 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[0]);
				}
				else
				{
					_param0 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[0]);
				}
				_param1 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_param0.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameActor)agent).findPath(((CInstanceMember<UnityEngine.Vector3>)_param0).GetValue(self), ((CInstanceMember<int>)_param1).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_getAvailabeMoveDirection : CAgentMethodBase<float>
		{
			IInstanceMember _param0;
			CInstanceMember<eMapDirection> _param1;

			public CMethod_GameLevelCommon_getAvailabeMoveDirection()
			{
			}

			public CMethod_GameLevelCommon_getAvailabeMoveDirection(CMethod_GameLevelCommon_getAvailabeMoveDirection rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_getAvailabeMoveDirection(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<GameActor>(paramStrs[0]);
				_param1 = (CInstanceMember<eMapDirection>)AgentMeta.ParseProperty<eMapDirection>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).getAvailabeMoveDirection((GameActor)_param0.GetValueObject(self), ((CInstanceMember<eMapDirection>)_param1).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_getBrickType : CAgentMethodBase<eBrickType>
		{
			IInstanceMember _param0;
			CInstanceMember<eMapDirection> _param1;
			CInstanceMember<int> _param2;

			public CMethod_GameLevelCommon_getBrickType()
			{
			}

			public CMethod_GameLevelCommon_getBrickType(CMethod_GameLevelCommon_getBrickType rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_getBrickType(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 3);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<GameActor>(paramStrs[0]);
				_param1 = (CInstanceMember<eMapDirection>)AgentMeta.ParseProperty<eMapDirection>(paramStrs[1]);
				_param2 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[2]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);
				Debug.Check(_param2 != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).getBrickType((GameActor)_param0.GetValueObject(self), ((CInstanceMember<eMapDirection>)_param1).GetValue(self), ((CInstanceMember<int>)_param2).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_getEnemyPosition : CAgentMethodBase<UnityEngine.Vector3>
		{
			IInstanceMember _param0;

			public CMethod_GameLevelCommon_getEnemyPosition()
			{
			}

			public CMethod_GameLevelCommon_getEnemyPosition(CMethod_GameLevelCommon_getEnemyPosition rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_getEnemyPosition(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<behaviac.Agent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).getEnemyPosition((behaviac.Agent)_param0.GetValueObject(self));
			}
		}

		private class CMethod_GameLevelCommon_spawnEffect : CAgentMethodBase<UnityEngine.Transform>
		{
			CInstanceMember<string> _param0;
			IInstanceMember _param1;
			CInstanceMember<UnityEngine.Vector3> _param2;
			CInstanceMember<float> _param3;

			public CMethod_GameLevelCommon_spawnEffect()
			{
			}

			public CMethod_GameLevelCommon_spawnEffect(CMethod_GameLevelCommon_spawnEffect rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_spawnEffect(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 4);

				_instance = instance;
				_param0 = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<UnityEngine.Transform>(paramStrs[1]);
				if (paramStrs[2].StartsWith("{"))
				{
					_param2 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[2]);
				}
				else
				{
					_param2 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[2]);
				}
				_param3 = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[3]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);
				Debug.Check(_param2 != null);
				Debug.Check(_param3 != null);

				_param2.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).spawnEffect(((CInstanceMember<string>)_param0).GetValue(self), (UnityEngine.Transform)_param1.GetValueObject(self), ((CInstanceMember<UnityEngine.Vector3>)_param2).GetValue(self), ((CInstanceMember<float>)_param3).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_spawnGameActor1 : CAgentMethodBase<int>
		{
			CInstanceMember<string> _param0;
			CInstanceMember<UnityEngine.Color> _param1;
			CInstanceMember<int> _param2;

			public CMethod_GameLevelCommon_spawnGameActor1()
			{
			}

			public CMethod_GameLevelCommon_spawnGameActor1(CMethod_GameLevelCommon_spawnGameActor1 rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_spawnGameActor1(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 3);

				_instance = instance;
				_param0 = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
				if (paramStrs[1].StartsWith("{"))
				{
					_param1 = new CInstanceConst_UnityEngine_Color("UnityEngine.Color", paramStrs[1]);
				}
				else
				{
					_param1 = (CInstanceMember<UnityEngine.Color>)AgentMeta.ParseProperty<UnityEngine.Color>(paramStrs[1]);
				}
				_param2 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[2]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);
				Debug.Check(_param2 != null);

				_param1.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).spawnGameActor1(((CInstanceMember<string>)_param0).GetValue(self), ((CInstanceMember<UnityEngine.Color>)_param1).GetValue(self), ((CInstanceMember<int>)_param2).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_spawnGameActor2 : CAgentMethodBase<int>
		{
			CInstanceMember<string> _param0;
			CInstanceMember<int> _param1;
			CInstanceMember<UnityEngine.Color> _param2;

			public CMethod_GameLevelCommon_spawnGameActor2()
			{
			}

			public CMethod_GameLevelCommon_spawnGameActor2(CMethod_GameLevelCommon_spawnGameActor2 rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_spawnGameActor2(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 3);

				_instance = instance;
				_param0 = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
				_param1 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
				if (paramStrs[2].StartsWith("{"))
				{
					_param2 = new CInstanceConst_UnityEngine_Color("UnityEngine.Color", paramStrs[2]);
				}
				else
				{
					_param2 = (CInstanceMember<UnityEngine.Color>)AgentMeta.ParseProperty<UnityEngine.Color>(paramStrs[2]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);
				Debug.Check(_param2 != null);

				_param2.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).spawnGameActor2(((CInstanceMember<string>)_param0).GetValue(self), ((CInstanceMember<int>)_param1).GetValue(self), ((CInstanceMember<UnityEngine.Color>)_param2).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_spawnGameActor3 : CAgentMethodBase<int>
		{
			CInstanceMember<string> _param0;
			CInstanceMember<UnityEngine.Color> _param1;

			public CMethod_GameLevelCommon_spawnGameActor3()
			{
			}

			public CMethod_GameLevelCommon_spawnGameActor3(CMethod_GameLevelCommon_spawnGameActor3 rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_spawnGameActor3(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
				if (paramStrs[1].StartsWith("{"))
				{
					_param1 = new CInstanceConst_UnityEngine_Color("UnityEngine.Color", paramStrs[1]);
				}
				else
				{
					_param1 = (CInstanceMember<UnityEngine.Color>)AgentMeta.ParseProperty<UnityEngine.Color>(paramStrs[1]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_param1.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).spawnGameActor3(((CInstanceMember<string>)_param0).GetValue(self), ((CInstanceMember<UnityEngine.Color>)_param1).GetValue(self));
			}
		}

		private class CMethod_GameLevelCommon_spawnGameActor4 : CAgentMethodBase<int>
		{
			CInstanceMember<eGameForce> _param0;
			CInstanceMember<string> _param1;
			CInstanceMember<int> _param2;
			CInstanceMember<UnityEngine.Color> _param3;
			CInstanceMember<int> _param4;

			public CMethod_GameLevelCommon_spawnGameActor4()
			{
			}

			public CMethod_GameLevelCommon_spawnGameActor4(CMethod_GameLevelCommon_spawnGameActor4 rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_GameLevelCommon_spawnGameActor4(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 5);

				_instance = instance;
				_param0 = (CInstanceMember<eGameForce>)AgentMeta.ParseProperty<eGameForce>(paramStrs[0]);
				_param1 = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[1]);
				_param2 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[2]);
				if (paramStrs[3].StartsWith("{"))
				{
					_param3 = new CInstanceConst_UnityEngine_Color("UnityEngine.Color", paramStrs[3]);
				}
				else
				{
					_param3 = (CInstanceMember<UnityEngine.Color>)AgentMeta.ParseProperty<UnityEngine.Color>(paramStrs[3]);
				}
				_param4 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[4]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);
				Debug.Check(_param2 != null);
				Debug.Check(_param3 != null);
				Debug.Check(_param4 != null);

				_param3.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((GameLevelCommon)agent).spawnGameActor4(((CInstanceMember<eGameForce>)_param0).GetValue(self), ((CInstanceMember<string>)_param1).GetValue(self), ((CInstanceMember<int>)_param2).GetValue(self), ((CInstanceMember<UnityEngine.Color>)_param3).GetValue(self), ((CInstanceMember<int>)_param4).GetValue(self));
			}
		}

		private class CMethod_Player_aimToTarget : CAgentMethodBase<behaviac.EBTStatus>
		{
			CInstanceMember<UnityEngine.Vector3> _param0;

			public CMethod_Player_aimToTarget()
			{
			}

			public CMethod_Player_aimToTarget(CMethod_Player_aimToTarget rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_aimToTarget(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				if (paramStrs[0].StartsWith("{"))
				{
					_param0 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[0]);
				}
				else
				{
					_param0 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[0]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_param0.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((Player)agent).aimToTarget(((CInstanceMember<UnityEngine.Vector3>)_param0).GetValue(self));
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				UnityEngine.Vector3 result = ((CInstanceMember<UnityEngine.Vector3>)firstParam).GetValue(self);
				_returnValue.value = ((Player)agent).aimToTarget(result);
				return _returnValue;
			}
		}

		private class CMethod_Player_getInfo : CAgentMethodVoidBase
		{
			CInstanceMember<float> _param0;
			CInstanceMember<int> _param1;

			public CMethod_Player_getInfo()
			{
			}

			public CMethod_Player_getInfo(CMethod_Player_getInfo rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_getInfo(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = (CInstanceMember<float>)AgentMeta.ParseProperty<float>(paramStrs[0]);
				_param1 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				float param0 = ((CInstanceMember<float>)_param0).GetValue(self);
				int param1 = ((CInstanceMember<int>)_param1).GetValue(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				((Player)agent).getInfo(ref param0, ref param1);
				_param0.SetValue(self, param0);
				_param1.SetValue(self, param1);
			}
		}

		private class CMethod_Player_getTarget : CAgentMethodVoidBase
		{
			CInstanceMember<UnityEngine.Vector3> _param0;

			public CMethod_Player_getTarget()
			{
			}

			public CMethod_Player_getTarget(CMethod_Player_getTarget rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_getTarget(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				if (paramStrs[0].StartsWith("{"))
				{
					_param0 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[0]);
				}
				else
				{
					_param0 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[0]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_param0.Run(self);
				UnityEngine.Vector3 param0 = ((CInstanceMember<UnityEngine.Vector3>)_param0).GetValue(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				((Player)agent).getTarget(ref param0);
				_param0.SetValue(self, param0);
			}
		}

		private class CMethod_Player_locationTendencyToTarget : CAgentMethodBase<eMapDirection>
		{
			CInstanceMember<UnityEngine.Vector3> _param0;

			public CMethod_Player_locationTendencyToTarget()
			{
			}

			public CMethod_Player_locationTendencyToTarget(CMethod_Player_locationTendencyToTarget rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_locationTendencyToTarget(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				if (paramStrs[0].StartsWith("{"))
				{
					_param0 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[0]);
				}
				else
				{
					_param0 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[0]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_param0.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((Player)agent).locationTendencyToTarget(((CInstanceMember<UnityEngine.Vector3>)_param0).GetValue(self));
			}
		}

		private class CMethod_Player_moveto : CAgentMethodBase<behaviac.EBTStatus>
		{
			CInstanceMember<UnityEngine.Vector3> _param0;

			public CMethod_Player_moveto()
			{
			}

			public CMethod_Player_moveto(CMethod_Player_moveto rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_moveto(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				if (paramStrs[0].StartsWith("{"))
				{
					_param0 = new CInstanceConst_UnityEngine_Vector3("UnityEngine.Vector3", paramStrs[0]);
				}
				else
				{
					_param0 = (CInstanceMember<UnityEngine.Vector3>)AgentMeta.ParseProperty<UnityEngine.Vector3>(paramStrs[0]);
				}
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_param0.Run(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				object[] paramArray = new object[] { ((CInstanceMember<UnityEngine.Vector3>)_param0).GetValue(self) };
				_returnValue.value = (behaviac.EBTStatus)AgentMetaVisitor.ExecuteMethod(((Player)agent), "moveto", paramArray);
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				UnityEngine.Vector3 result = ((CInstanceMember<UnityEngine.Vector3>)firstParam).GetValue(self);
				object[] paramArray = new object[] { result };
				_returnValue.value = (behaviac.EBTStatus)AgentMetaVisitor.ExecuteMethod(((Player)agent), "moveto", paramArray);
				return _returnValue;
			}
		}

		private class CMethod_Player_predicateFirePoint : CAgentMethodBase<UnityEngine.Vector3>
		{
			IInstanceMember _param0;

			public CMethod_Player_predicateFirePoint()
			{
			}

			public CMethod_Player_predicateFirePoint(CMethod_Player_predicateFirePoint rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_Player_predicateFirePoint(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<behaviac.Agent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((Player)agent).predicateFirePoint((behaviac.Agent)_param0.GetValueObject(self));
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 2027039838;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// GameActor
			meta = new AgentMeta(1101269840);
			AgentMeta._AgentMetas_[1627260109] = meta;
			meta.RegisterMemberProperty(2753746913, new CMemberProperty<float>("currentOrientation", delegate(Agent self, float value) { ((GameActor)self).currentOrientation = value; }, delegate(Agent self) { return ((GameActor)self).currentOrientation; }));
			meta.RegisterMemberProperty(1756701828, new CMemberProperty<eGameForce>("force", delegate(Agent self, eGameForce value) { ((GameActor)self).force = value; }, delegate(Agent self) { return ((GameActor)self).force; }));
			meta.RegisterMemberProperty(4158177446, new CMemberProperty<int>("gameScore", delegate(Agent self, int value) { ((GameActor)self).gameScore = value; }, delegate(Agent self) { return ((GameActor)self).gameScore; }));
			meta.RegisterMethod(4199097511, new CMethod_GameActor_findPath());
			meta.RegisterMethod(1626091144, new CAgentMethod<eMapDirection, eMapDirection>(delegate(Agent self, eMapDirection param0) { return ((GameActor)self).getBestMoveDirection(param0); }));
			meta.RegisterMethod(3755356592, new CAgentMethod<int>(delegate(Agent self) { return ((GameActor)self).getPathDistance(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { GameActor.LogMessage(param0); }));
			meta.RegisterMethod(3252698044, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((GameActor)self).moveForward(); }));
			meta.RegisterMethod(1961188964, new CAgentMethod<behaviac.EBTStatus, eMapDirection>(delegate(Agent self, eMapDirection param0) { return ((GameActor)self).moveToDirection(param0); }));
			meta.RegisterMethod(3698607782, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((GameActor)self).navigate(); }));
			meta.RegisterMethod(2618631093, new CAgentMethod<behaviac.EBTStatus, float>(delegate(Agent self, float param0) { return ((GameActor)self).rotateToAngle(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// GameLevelCommon
			meta = new AgentMeta(2048302510);
			AgentMeta._AgentMetas_[1628794678] = meta;
			meta.RegisterMemberProperty(3158683272, new CStaticMemberProperty<int>("actorWalkLevel", delegate(int value) { GameLevelCommon.actorWalkLevel = value; }, delegate() { return GameLevelCommon.actorWalkLevel; }));
			meta.RegisterMemberProperty(2745407180, new CStaticMemberProperty<int>("allWalkLevel", delegate(int value) { GameLevelCommon.allWalkLevel = value; }, delegate() { return GameLevelCommon.allWalkLevel; }));
			meta.RegisterMemberProperty(986146567, new CStaticMemberProperty<int>("bulletWalkLevel", delegate(int value) { GameLevelCommon.bulletWalkLevel = value; }, delegate() { return GameLevelCommon.bulletWalkLevel; }));
			meta.RegisterMemberProperty(592530272, new CStaticMemberProperty<int>("defaultWalkLevel", delegate(int value) { GameLevelCommon.defaultWalkLevel = value; }, delegate() { return GameLevelCommon.defaultWalkLevel; }));
			meta.RegisterMemberProperty(70435140, new CMemberProperty<bool>("isPlayerAlive", delegate(Agent self, bool value) { ((GameLevelCommon)self).isPlayerAlive = value; }, delegate(Agent self) { return ((GameLevelCommon)self).isPlayerAlive; }));
			meta.RegisterMemberProperty(707149732, new CStaticMemberProperty<int>("soilSteelOceanWalkLevel", delegate(int value) { GameLevelCommon.soilSteelOceanWalkLevel = value; }, delegate() { return GameLevelCommon.soilSteelOceanWalkLevel; }));
			meta.RegisterMemberProperty(4227530859, new CStaticMemberProperty<int>("soilSteelWalkLevel", delegate(int value) { GameLevelCommon.soilSteelWalkLevel = value; }, delegate() { return GameLevelCommon.soilSteelWalkLevel; }));
			meta.RegisterMemberProperty(4263539745, new CStaticMemberProperty<int>("soilWalkLevel", delegate(int value) { GameLevelCommon.soilWalkLevel = value; }, delegate() { return GameLevelCommon.soilWalkLevel; }));
			meta.RegisterMethod(264642526, new CAgentMethodVoid(delegate(Agent self) { ((GameLevelCommon)self).continueGame(); }));
			meta.RegisterMethod(30218961, new CAgentMethod<int, int>(delegate(Agent self, int param0) { return ((GameLevelCommon)self).getActorLifeCount(param0); }));
			meta.RegisterMethod(3548626221, new CMethod_GameLevelCommon_getAvailabeMoveDirection());
			meta.RegisterMethod(436701902, new CAgentMethod<UnityEngine.Vector3, int>(delegate(Agent self, int param0) { return ((GameLevelCommon)self).getAwardPosition(param0); }));
			meta.RegisterMethod(2965064745, new CMethod_GameLevelCommon_getBrickType());
			meta.RegisterMethod(544003837, new CAgentStaticMethod<UnityEngine.Color, List<UnityEngine.Color>, int>(delegate(List<UnityEngine.Color> param0, int param1) { return GameLevelCommon.getColorArrayElement(param0, param1); }));
			meta.RegisterMethod(117177237, new CAgentMethod<int>(delegate(Agent self) { return ((GameLevelCommon)self).getEnemyCount(); }));
			meta.RegisterMethod(3697387725, new CMethod_GameLevelCommon_getEnemyPosition());
			meta.RegisterMethod(376329892, new CAgentStaticMethod<eGameForce, List<eGameForce>, int>(delegate(List<eGameForce> param0, int param1) { return GameLevelCommon.getGameForceArrayElement(param0, param1); }));
			meta.RegisterMethod(837399323, new CAgentStaticMethod<int, List<int>, int>(delegate(List<int> param0, int param1) { return GameLevelCommon.getIntArrayElement(param0, param1); }));
			meta.RegisterMethod(245727536, new CAgentMethod<int>(delegate(Agent self) { return ((GameLevelCommon)self).getNearestAwardID(); }));
			meta.RegisterMethod(3067406351, new CAgentMethod<behaviac.Agent, eGameForce>(delegate(Agent self, eGameForce param0) { return ((GameLevelCommon)self).getNearestEnemy(param0); }));
			meta.RegisterMethod(3589271143, new CAgentMethod<behaviac.Agent>(delegate(Agent self) { return ((GameLevelCommon)self).getPlayer(); }));
			meta.RegisterMethod(570880473, new CAgentStaticMethod<string, List<string>, int>(delegate(List<string> param0, int param1) { return GameLevelCommon.getStringArrayElement(param0, param1); }));
			meta.RegisterMethod(1207213688, new CAgentMethod<behaviac.EBTStatus, int>(delegate(Agent self, int param0) { return ((GameLevelCommon)self).isActorAlive(param0); }));
			meta.RegisterMethod(3613902360, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((GameLevelCommon)self).isAllEnemyDeadForever(); }));
			meta.RegisterMethod(934651765, new CAgentMethod<bool, int>(delegate(Agent self, int param0) { return ((GameLevelCommon)self).isAwardExist(param0); }));
			meta.RegisterMethod(2593994091, new CAgentMethod<bool, eBrickType, int>(delegate(Agent self, eBrickType param0, int param1) { return ((GameLevelCommon)self).isBrickTypeWakable(param0, param1); }));
			meta.RegisterMethod(2324673246, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((GameLevelCommon)self).isPlayerDeadForever(); }));
			meta.RegisterMethod(189354342, new CAgentMethod<bool, int, int, int>(delegate(Agent self, int param0, int param1, int param2) { return ((GameLevelCommon)self).isPointWakable(param0, param1, param2); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { GameLevelCommon.LogMessage(param0); }));
			meta.RegisterMethod(2402022264, new CAgentMethod<float, float, float>(delegate(Agent self, float param0, float param1) { return ((GameLevelCommon)self).randomNumberFloat(param0, param1); }));
			meta.RegisterMethod(836754027, new CAgentMethod<int, int, int>(delegate(Agent self, int param0, int param1) { return ((GameLevelCommon)self).randomNumberInt(param0, param1); }));
			meta.RegisterMethod(616993231, new CAgentMethodVoid<int, int>(delegate(Agent self, int param0, int param1) { ((GameLevelCommon)self).setActorLifeCount(param0, param1); }));
			meta.RegisterMethod(4216187258, new CAgentMethodVoid<int>(delegate(Agent self, int param0) { ((GameLevelCommon)self).setMainCharID(param0); }));
			meta.RegisterMethod(785913501, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((GameLevelCommon)self).showCredit(); }));
			meta.RegisterMethod(2309507932, new CAgentMethod<behaviac.EBTStatus, int, int, int, float>(delegate(Agent self, int param0, int param1, int param2, float param3) { return ((GameLevelCommon)self).spawnAward(param0, param1, param2, param3); }));
			meta.RegisterMethod(39741690, new CMethod_GameLevelCommon_spawnEffect());
			meta.RegisterMethod(40725768, new CMethod_GameLevelCommon_spawnGameActor1());
			meta.RegisterMethod(692076235, new CMethod_GameLevelCommon_spawnGameActor2());
			meta.RegisterMethod(811274122, new CMethod_GameLevelCommon_spawnGameActor3());
			meta.RegisterMethod(2132449613, new CMethod_GameLevelCommon_spawnGameActor4());
			meta.RegisterMethod(2412112748, new CAgentMethod<int, eGameForce>(delegate(Agent self, eGameForce param0) { return ((GameLevelCommon)self).spawnRandomActor(param0); }));
			meta.RegisterMethod(2970214778, new CAgentMethodVoid<bool>(delegate(Agent self, bool param0) { ((GameLevelCommon)self).stopGame(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// Player
			meta = new AgentMeta(2267513020);
			AgentMeta._AgentMetas_[912457846] = meta;
			meta.RegisterMemberProperty(2753746913, new CMemberProperty<float>("currentOrientation", delegate(Agent self, float value) { ((Player)self).currentOrientation = value; }, delegate(Agent self) { return ((Player)self).currentOrientation; }));
			meta.RegisterMemberProperty(622841434, new CMemberProperty<int>("damageLevel", delegate(Agent self, int value) { ((Player)self).damageLevel = value; }, delegate(Agent self) { return ((Player)self).damageLevel; }));
			meta.RegisterMemberProperty(1756701828, new CMemberProperty<eGameForce>("force", delegate(Agent self, eGameForce value) { ((Player)self).force = value; }, delegate(Agent self) { return ((Player)self).force; }));
			meta.RegisterMemberProperty(4158177446, new CMemberProperty<int>("gameScore", delegate(Agent self, int value) { ((Player)self).gameScore = value; }, delegate(Agent self) { return ((Player)self).gameScore; }));
			meta.RegisterMemberProperty(2269881519, new CMemberProperty<int>("hp", delegate(Agent self, int value) { ((Player)self).hp = value; }, delegate(Agent self) { return ((Player)self).hp; }));
			meta.RegisterMemberProperty(767337018, new CMemberProperty<int>("Index", delegate(Agent self, int value) { ((Player)self).Index = value; }, delegate(Agent self) { return ((Player)self).Index; }));
			meta.RegisterCustomizedProperty(525979889, new CCustomizedProperty<behaviac.EBTStatus>(525979889, "Status", "BT_INVALID"));
			meta.RegisterMethod(3557495925, new CAgentMethod<behaviac.EBTStatus, float>(delegate(Agent self, float param0) { return ((Player)self).aimToAngle(param0); }));
			meta.RegisterMethod(3177487640, new CMethod_Player_aimToTarget());
			meta.RegisterMethod(2668400177, new CAgentMethod<behaviac.EBTStatus, int>(delegate(Agent self, int param0) { return ((Player)self).canDestroyBrick(param0); }));
			meta.RegisterMethod(2108158066, new CAgentMethod<int, eMapDirection>(delegate(Agent self, eMapDirection param0) { return ((Player)self).detectEnemy(param0); }));
			meta.RegisterMethod(123494839, new CAgentMethod<float>(delegate(Agent self) { return ((Player)self).detectNearestEnemyInView(); }));
			meta.RegisterMethod(1386074925, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((Player)self).findNearestEnemy(); }));
			meta.RegisterMethod(4199097511, new CMethod_GameActor_findPath());
			meta.RegisterMethod(554947907, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((Player)self).fire(); }));
			meta.RegisterMethod(1626091144, new CAgentMethod<eMapDirection, eMapDirection>(delegate(Agent self, eMapDirection param0) { return ((Player)self).getBestMoveDirection(param0); }));
			meta.RegisterMethod(3079621360, new CMethod_Player_getInfo());
			meta.RegisterMethod(3755356592, new CAgentMethod<int>(delegate(Agent self) { return ((Player)self).getPathDistance(); }));
			meta.RegisterMethod(1558361042, new CMethod_Player_getTarget());
			meta.RegisterMethod(3199795965, new CMethod_Player_locationTendencyToTarget());
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { Player.LogMessage(param0); }));
			meta.RegisterMethod(3252698044, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((Player)self).moveForward(); }));
			meta.RegisterMethod(1405399204, new CMethod_Player_moveto());
			meta.RegisterMethod(1961188964, new CAgentMethod<behaviac.EBTStatus, eMapDirection>(delegate(Agent self, eMapDirection param0) { return ((Player)self).moveToDirection(param0); }));
			meta.RegisterMethod(3698607782, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((Player)self).navigate(); }));
			meta.RegisterMethod(354068350, new CMethod_Player_predicateFirePoint());
			meta.RegisterMethod(251027700, new CAgentMethodVoid<float, int>(delegate(Agent self, float param0, int param1) { ((Player)self).printf(param0, param1); }));
			meta.RegisterMethod(2618631093, new CAgentMethod<behaviac.EBTStatus, float>(delegate(Agent self, float param0) { return ((Player)self).rotateToAngle(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<GameActor>("GameActor");
			AgentMeta.Register<GameLevelCommon>("GameLevelCommon");
			AgentMeta.Register<Player>("Player");
			AgentMeta.Register<behaviac.EBTStatus>("behaviac.EBTStatus");
			ComparerRegister.RegisterType<behaviac.EBTStatus, CompareValue_behaviac_EBTStatus>();
			AgentMeta.Register<eGameForce>("eGameForce");
			ComparerRegister.RegisterType<eGameForce, CompareValue_eGameForce>();
			AgentMeta.Register<eMapDirection>("eMapDirection");
			ComparerRegister.RegisterType<eMapDirection, CompareValue_eMapDirection>();
			AgentMeta.Register<eBrickType>("eBrickType");
			ComparerRegister.RegisterType<eBrickType, CompareValue_eBrickType>();
			AgentMeta.Register<UnityEngine.Vector3>("UnityEngine.Vector3");
			ComparerRegister.RegisterType<UnityEngine.Vector3, CompareValue_UnityEngine_Vector3>();
			AgentMeta.Register<UnityEngine.Color>("UnityEngine.Color");
			ComparerRegister.RegisterType<UnityEngine.Color, CompareValue_UnityEngine_Color>();
			AgentMeta.Register<UnityEngine.Transform>("UnityEngine.Transform");
			ComparerRegister.RegisterType<UnityEngine.Transform, CompareValue_UnityEngine_Transform>();

			Agent.RegisterInstanceName<GameLevelCommon>("GameLevel");
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<GameActor>("GameActor");
			AgentMeta.UnRegister<GameLevelCommon>("GameLevelCommon");
			AgentMeta.UnRegister<Player>("Player");
			AgentMeta.UnRegister<behaviac.EBTStatus>("behaviac.EBTStatus");
			AgentMeta.UnRegister<eGameForce>("eGameForce");
			AgentMeta.UnRegister<eMapDirection>("eMapDirection");
			AgentMeta.UnRegister<eBrickType>("eBrickType");
			AgentMeta.UnRegister<UnityEngine.Vector3>("UnityEngine.Vector3");
			AgentMeta.UnRegister<UnityEngine.Color>("UnityEngine.Color");
			AgentMeta.UnRegister<UnityEngine.Transform>("UnityEngine.Transform");

			Agent.UnRegisterInstanceName<GameLevelCommon>("GameLevel");
			return true;
		}
	}
}
